//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleMatricula
    {
        public int IIDMATRICULA { get; set; }
        public int IIDCURSO { get; set; }
        public Nullable<decimal> NOTA1 { get; set; }
        public Nullable<decimal> NOTA2 { get; set; }
        public Nullable<decimal> NOTA3 { get; set; }
        public Nullable<decimal> NOTA4 { get; set; }
        public Nullable<decimal> PROMEDIO { get; set; }
        public Nullable<int> bhabilitado { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Matricula Matricula { get; set; }
    }
}
