//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodoGradoCurso
    {
        public int IID { get; set; }
        public Nullable<int> IIDPERIODO { get; set; }
        public Nullable<int> IIDGRADO { get; set; }
        public Nullable<int> IIDCURSO { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Grado Grado { get; set; }
        public virtual Periodo Periodo { get; set; }
    }
}
