//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SistemaMatriculaEntities : DbContext
    {
        public SistemaMatriculaEntities()
            : base("name=SistemaMatriculaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumno { get; set; }
        public virtual DbSet<Aula> Aula { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<DetalleMatricula> DetalleMatricula { get; set; }
        public virtual DbSet<Docente> Docente { get; set; }
        public virtual DbSet<DocentePeriodo> DocentePeriodo { get; set; }
        public virtual DbSet<Grado> Grado { get; set; }
        public virtual DbSet<GradoSeccion> GradoSeccion { get; set; }
        public virtual DbSet<GradoSeccionAula> GradoSeccionAula { get; set; }
        public virtual DbSet<Matricula> Matricula { get; set; }
        public virtual DbSet<ModalidadContrato> ModalidadContrato { get; set; }
        public virtual DbSet<Periodo> Periodo { get; set; }
        public virtual DbSet<PeriodoGradoCurso> PeriodoGradoCurso { get; set; }
        public virtual DbSet<Seccion> Seccion { get; set; }
        public virtual DbSet<Sexo> Sexo { get; set; }
    }
}
